package com.coderslab.entity;
// Generated Oct 25, 2017 11:48:19 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Comments generated by hbm2java
 */
@Entity
@Table(name = "comments",
         catalog = "bes"
)
public class Comments implements java.io.Serializable {

    private Integer commentsId;
    private String username;
    private int topicsId;
    private String comment;

    public Comments() {
    }

    public Comments(String username, int topicsId, String comment) {
        this.username = username;
        this.topicsId = topicsId;
        this.comment = comment;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "commentsId", unique = true, nullable = false)
    public Integer getCommentsId() {
        return this.commentsId;
    }

    public void setCommentsId(Integer commentsId) {
        this.commentsId = commentsId;
    }

    @Column(name = "username", nullable = false, length = 60)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "topicsId", nullable = false)
    public int getTopicsId() {
        return this.topicsId;
    }

    public void setTopicsId(int topicsId) {
        this.topicsId = topicsId;
    }

    @Column(name = "comment", nullable = false, length = 65535)
    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @Override
    public String toString() {
        return "Comments{" + "commentsId=" + commentsId + ", username=" + username + ", topicsId=" + topicsId + ", comment=" + comment + '}';
    }

}
