package com.coderslab.entity;
// Generated Oct 26, 2017 8:09:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name="event"
    ,catalog="bes"
)
public class Event  implements java.io.Serializable {


     private Integer eventId;
     private String eventName;
     private String username;
     private String videoUrl;
     private String notesFile;
     private String presentationFile;
     private String eventCreatorName;
     private String description;
     private String eventPhoto;
     private Date eventDate;
     private boolean status;

    public Event() {
    }

	
    public Event(String eventName, String username, String videoUrl, String eventCreatorName, Date eventDate, boolean status) {
        this.eventName = eventName;
        this.username = username;
        this.videoUrl = videoUrl;
        this.eventCreatorName = eventCreatorName;
        this.eventDate = eventDate;
        this.status = status;
    }
    public Event(String eventName, String username, String videoUrl, String notesFile, String presentationFile, String eventCreatorName, String description, String eventPhoto, Date eventDate, boolean status) {
       this.eventName = eventName;
       this.username = username;
       this.videoUrl = videoUrl;
       this.notesFile = notesFile;
       this.presentationFile = presentationFile;
       this.eventCreatorName = eventCreatorName;
       this.description = description;
       this.eventPhoto = eventPhoto;
       this.eventDate = eventDate;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="eventId", unique=true, nullable=false)
    public Integer getEventId() {
        return this.eventId;
    }
    
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    
    @Column(name="eventName", nullable=false, length=100)
    public String getEventName() {
        return this.eventName;
    }
    
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }

    
    @Column(name="username", nullable=false, length=60)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="videoUrl", nullable=false, length=65535)
    public String getVideoUrl() {
        return this.videoUrl;
    }
    
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    
    @Column(name="notesFile", length=65535)
    public String getNotesFile() {
        return this.notesFile;
    }
    
    public void setNotesFile(String notesFile) {
        this.notesFile = notesFile;
    }

    
    @Column(name="presentationFile", length=65535)
    public String getPresentationFile() {
        return this.presentationFile;
    }
    
    public void setPresentationFile(String presentationFile) {
        this.presentationFile = presentationFile;
    }

    
    @Column(name="eventCreatorName", nullable=false, length=100)
    public String getEventCreatorName() {
        return this.eventCreatorName;
    }
    
    public void setEventCreatorName(String eventCreatorName) {
        this.eventCreatorName = eventCreatorName;
    }

    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="eventPhoto", length=65535)
    public String getEventPhoto() {
        return this.eventPhoto;
    }
    
    public void setEventPhoto(String eventPhoto) {
        this.eventPhoto = eventPhoto;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="eventDate", nullable=false, length=19)
    public Date getEventDate() {
        return this.eventDate;
    }
    
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }

    
    @Column(name="status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


