package com.coderslab.entity;
// Generated Nov 3, 2017 3:08:12 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LessonExamResult generated by hbm2java
 */
@Entity
@Table(name = "lesson_exam_result",
        catalog = "bes"
)
public class LessonExamResult implements java.io.Serializable {

    private Integer resultId;
    private String username;
    private int lessonId;
    private String lessonName;
    private int totalQuestion;
    private int passMark;
    private int correctAnswer;
    private int wrongAnswer;
    private String passingStatus;
    private Date examDate;

    public LessonExamResult() {
    }

    public LessonExamResult(String username, int lessonId, String lessonName, int totalQuestion, int passMark, int correctAnswer, int wrongAnswer, String passingStatus, Date examDate) {
        this.username = username;
        this.lessonId = lessonId;
        this.lessonName = lessonName;
        this.totalQuestion = totalQuestion;
        this.passMark = passMark;
        this.correctAnswer = correctAnswer;
        this.wrongAnswer = wrongAnswer;
        this.passingStatus = passingStatus;
        this.examDate = examDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "resultId", unique = true, nullable = false)
    public Integer getResultId() {
        return this.resultId;
    }

    public void setResultId(Integer resultId) {
        this.resultId = resultId;
    }

    @Column(name = "username", nullable = false, length = 60)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "lessonId", nullable = false)
    public int getLessonId() {
        return this.lessonId;
    }

    public void setLessonId(int lessonId) {
        this.lessonId = lessonId;
    }

    @Column(name = "lessonName", nullable = false, length = 65535)
    public String getLessonName() {
        return this.lessonName;
    }

    public void setLessonName(String lessonName) {
        this.lessonName = lessonName;
    }

    @Column(name = "totalQuestion", nullable = false)
    public int getTotalQuestion() {
        return this.totalQuestion;
    }

    public void setTotalQuestion(int totalQuestion) {
        this.totalQuestion = totalQuestion;
    }

    @Column(name = "passMark", nullable = false)
    public int getPassMark() {
        return this.passMark;
    }

    public void setPassMark(int passMark) {
        this.passMark = passMark;
    }

    @Column(name = "correctAnswer", nullable = false)
    public int getCorrectAnswer() {
        return this.correctAnswer;
    }

    public void setCorrectAnswer(int correctAnswer) {
        this.correctAnswer = correctAnswer;
    }

    @Column(name = "wrongAnswer", nullable = false)
    public int getWrongAnswer() {
        return this.wrongAnswer;
    }

    public void setWrongAnswer(int wrongAnswer) {
        this.wrongAnswer = wrongAnswer;
    }

    @Column(name = "passingStatus", nullable = false, length = 40)
    public String getPassingStatus() {
        return this.passingStatus;
    }

    public void setPassingStatus(String passingStatus) {
        this.passingStatus = passingStatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "examDate", nullable = false, length = 10)
    public Date getExamDate() {
        return this.examDate;
    }

    public void setExamDate(Date examDate) {
        this.examDate = examDate;
    }

    @Override
    public String toString() {
        return "LessonExamResult{" + "resultId=" + resultId + ", username=" + username + ", lessonId=" + lessonId + ", lessonName=" + lessonName + ", totalQuestion=" + totalQuestion + ", passMark=" + passMark + ", correntAnswer=" + correctAnswer + ", wrongAnswer=" + wrongAnswer + ", passingStatus=" + passingStatus + ", examDate=" + examDate + '}';
    }

}
