package com.coderslab.entity;
// Generated Oct 28, 2017 11:34:24 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * Lesson generated by hbm2java
 */
@Entity
@Table(name = "lesson",
         catalog = "bes"
)
@NamedQueries({
    @NamedQuery(name = "Lesson.findLessonWithCourseByLessonId", query = "select distinct l from Lesson l left join fetch l.course c where l.lessonId = :lessonId")
    ,
@NamedQuery(name = "Lesson.findAllDataWithCourse", query = "select distinct l from Lesson l left join fetch l.course c")
    ,
@NamedQuery(name = "Lesson.findAllDataWithCourseAndTopics", query = "select distinct l from Lesson l left join fetch l.course c left join fetch l.topicses t")
})
public class Lesson implements java.io.Serializable {

    private Integer lessonId;
    private Course course;
    private String description;
    private Integer lessonDuration;
    private String lessonTitle;
    private String notesFile;
    private String presentationFile;
    private boolean status;
    private Set<Topics> topicses = new HashSet<Topics>(0);

    public Lesson() {
    }

    public Lesson(Course course, String lessonTitle, boolean status) {
        this.course = course;
        this.lessonTitle = lessonTitle;
        this.status = status;
    }

    public Lesson(Course course, String description, Integer lessonDuration, String lessonTitle, String notesFile, String presentationFile, boolean status, Set<Topics> topicses) {
        this.course = course;
        this.description = description;
        this.lessonDuration = lessonDuration;
        this.lessonTitle = lessonTitle;
        this.notesFile = notesFile;
        this.presentationFile = presentationFile;
        this.status = status;
        this.topicses = topicses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "lessonId", unique = true, nullable = false)
    public Integer getLessonId() {
        return this.lessonId;
    }

    public void setLessonId(Integer lessonId) {
        this.lessonId = lessonId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "courseId", nullable = false)
    public Course getCourse() {
        return this.course;
    }

    public void setCourse(Course course) {
        this.course = course;
    }

    @Column(name = "description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "lessonDuration")
    public Integer getLessonDuration() {
        return this.lessonDuration;
    }

    public void setLessonDuration(Integer lessonDuration) {
        this.lessonDuration = lessonDuration;
    }

    @Column(name = "lessonTitle", nullable = false)
    public String getLessonTitle() {
        return this.lessonTitle;
    }

    public void setLessonTitle(String lessonTitle) {
        this.lessonTitle = lessonTitle;
    }

    @Column(name = "notesFile")
    public String getNotesFile() {
        return this.notesFile;
    }

    public void setNotesFile(String notesFile) {
        this.notesFile = notesFile;
    }

    @Column(name = "presentationFile")
    public String getPresentationFile() {
        return this.presentationFile;
    }

    public void setPresentationFile(String presentationFile) {
        this.presentationFile = presentationFile;
    }

    @Column(name = "status", nullable = false)
    public boolean isStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "lesson")
    public Set<Topics> getTopicses() {
        return this.topicses;
    }

    public void setTopicses(Set<Topics> topicses) {
        this.topicses = topicses;
    }

    @Override
    public String toString() {
        return "Lesson{" + "lessonId=" + lessonId + ", course=" + course + ", description=" + description + ", lessonDuration=" + lessonDuration + ", lessonTitle=" + lessonTitle + ", notesFile=" + notesFile + ", presentationFile=" + presentationFile + ", status=" + status + ", topicses=" + topicses + '}';
    }

}
