package com.coderslab.entity;
// Generated Nov 22, 2017 11:40:13 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Posts generated by hbm2java
 */
@Entity
@Table(name = "posts",
         catalog = "bes"
)
public class Posts implements java.io.Serializable {

    private Integer postId;
    private String postTitle;
    private String postSubTitle;
    private String postContent;
    private int postShorten;
    private String subCategoryId;
    private String authorName;
    private boolean status;
    private Date postDate;
    private String image;
    private int views;

    public Posts() {
    }

    public Posts(String postTitle, String postContent, int postShorten, String subCategoryId, String authorName, boolean status, Date postDate, int views) {
        this.postTitle = postTitle;
        this.postContent = postContent;
        this.postShorten = postShorten;
        this.subCategoryId = subCategoryId;
        this.authorName = authorName;
        this.status = status;
        this.postDate = postDate;
        this.views = views;
    }

    public Posts(String postTitle, String postSubTitle, String postContent, int postShorten, String subCategoryId, String authorName, boolean status, Date postDate, String image, int views) {
        this.postTitle = postTitle;
        this.postSubTitle = postSubTitle;
        this.postContent = postContent;
        this.postShorten = postShorten;
        this.subCategoryId = subCategoryId;
        this.authorName = authorName;
        this.status = status;
        this.postDate = postDate;
        this.image = image;
        this.views = views;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "postId", unique = true, nullable = false)
    public Integer getPostId() {
        return this.postId;
    }

    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    @Column(name = "postTitle", nullable = false, length = 200)
    public String getPostTitle() {
        return this.postTitle;
    }

    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle;
    }

    @Column(name = "postSubTitle", length = 45)
    public String getPostSubTitle() {
        return this.postSubTitle;
    }

    public void setPostSubTitle(String postSubTitle) {
        this.postSubTitle = postSubTitle;
    }

    @Column(name = "postContent", nullable = false, length = 65535)
    public String getPostContent() {
        return this.postContent;
    }

    public void setPostContent(String postContent) {
        this.postContent = postContent;
    }

    @Column(name = "postShorten", nullable = false)
    public int getPostShorten() {
        return this.postShorten;
    }

    public void setPostShorten(int postShorten) {
        this.postShorten = postShorten;
    }

    @Column(name = "subCategoryId", nullable = false, length = 50)
    public String getSubCategoryId() {
        return this.subCategoryId;
    }

    public void setSubCategoryId(String subCategoryId) {
        this.subCategoryId = subCategoryId;
    }

    @Column(name = "authorName", nullable = false, length = 45)
    public String getAuthorName() {
        return this.authorName;
    }

    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    @Column(name = "status", nullable = false)
    public boolean isStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "postDate", nullable = false, length = 19)
    public Date getPostDate() {
        return this.postDate;
    }

    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }

    @Column(name = "image", length = 65535)
    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    @Column(name = "views", nullable = false)
    public int getViews() {
        return this.views;
    }

    public void setViews(int views) {
        this.views = views;
    }

    @Override
    public String toString() {
        return "Posts{" + "postId=" + postId + ", postTitle=" + postTitle + ", postSubTitle=" + postSubTitle + ", postContent=" + postContent + ", postShorten=" + postShorten + ", subCategoryId=" + subCategoryId + ", authorName=" + authorName + ", status=" + status + ", postDate=" + postDate + ", image=" + image + ", views=" + views + '}';
    }
    
    

}
