package com.coderslab.entity;
// Generated Nov 2, 2017 9:59:58 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "question",
         catalog = "bes"
)
public class Question implements java.io.Serializable {

    private Integer questionId;
    private String question;
    private String aone;
    private String atwo;
    private String athree;
    private String afour;
    private String canswer;
    private Integer lessonId;
    private Integer eventId;
    private String userName;
    private boolean status;

    public Question() {
    }

    public Question(String question, String aone, String atwo, String athree, String afour, String canswer, boolean status) {
        this.question = question;
        this.aone = aone;
        this.atwo = atwo;
        this.athree = athree;
        this.afour = afour;
        this.canswer = canswer;
        this.status = status;
    }

    public Question(String question, String aone, String atwo, String athree, String afour, String canswer, Integer lessonId, Integer eventId, String userName, boolean status) {
        this.question = question;
        this.aone = aone;
        this.atwo = atwo;
        this.athree = athree;
        this.afour = afour;
        this.canswer = canswer;
        this.lessonId = lessonId;
        this.eventId = eventId;
        this.userName = userName;
        this.status = status;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "questionId", unique = true, nullable = false)
    public Integer getQuestionId() {
        return this.questionId;
    }

    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    @Column(name = "question", nullable = false, length = 65535)
    public String getQuestion() {
        return this.question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    @Column(name = "aOne", nullable = false, length = 65535)
    public String getAone() {
        return this.aone;
    }

    public void setAone(String aone) {
        this.aone = aone;
    }

    @Column(name = "aTwo", nullable = false, length = 65535)
    public String getAtwo() {
        return this.atwo;
    }

    public void setAtwo(String atwo) {
        this.atwo = atwo;
    }

    @Column(name = "aThree", nullable = false, length = 65535)
    public String getAthree() {
        return this.athree;
    }

    public void setAthree(String athree) {
        this.athree = athree;
    }

    @Column(name = "aFour", nullable = false, length = 65535)
    public String getAfour() {
        return this.afour;
    }

    public void setAfour(String afour) {
        this.afour = afour;
    }

    @Column(name = "cAnswer", nullable = false, length = 45)
    public String getCanswer() {
        return this.canswer;
    }

    public void setCanswer(String canswer) {
        this.canswer = canswer;
    }

    @Column(name = "lessonId")
    public Integer getLessonId() {
        return this.lessonId;
    }

    public void setLessonId(Integer lessonId) {
        this.lessonId = lessonId;
    }

    @Column(name = "eventId")
    public Integer getEventId() {
        return this.eventId;
    }

    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    @Column(name = "userName", length = 60)
    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Column(name = "status", nullable = false)
    public boolean isStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "Question{" + "qid=" + questionId + ", question=" + question + ", aone=" + aone + ", atwo=" + atwo + ", athree=" + athree + ", afour=" + afour + ", canswer=" + canswer + ", lessonId=" + lessonId + ", eventId=" + eventId + ", userName=" + userName + ", status=" + status + '}';
    }

}
