package com.coderslab.entity;
// Generated Dec 17, 2017 10:50:11 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ratings generated by hbm2java
 */
@Entity
@Table(name = "ratings",
        catalog = "bes"
)
public class Ratings implements java.io.Serializable {

    private Integer ratingId;
    private Integer rating;
    private Integer postId;
    private Integer topicsId;
    private Integer eventId;
    private String username;

    public Ratings() {
    }

    public Ratings(String username) {
        this.username = username;
    }

    public Ratings(Integer rating, Integer postId, Integer topicsId, Integer eventId, String username) {
        this.rating = rating;
        this.postId = postId;
        this.topicsId = topicsId;
        this.eventId = eventId;
        this.username = username;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ratingId", unique = true, nullable = false)
    public Integer getRatingId() {
        return this.ratingId;
    }

    public void setRatingId(Integer ratingId) {
        this.ratingId = ratingId;
    }

    @Column(name = "rating")
    public Integer getRating() {
        return this.rating;
    }

    public void setRating(Integer rating) {
        this.rating = rating;
    }

    @Column(name = "postId")
    public Integer getPostId() {
        return this.postId;
    }

    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    @Column(name = "topicsId")
    public Integer getTopicsId() {
        return this.topicsId;
    }

    public void setTopicsId(Integer topicsId) {
        this.topicsId = topicsId;
    }

    @Column(name = "eventId")
    public Integer getEventId() {
        return this.eventId;
    }

    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    @Column(name = "username", nullable = false, length = 45)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String toString() {
        return "Ratings{" + "ratingId=" + ratingId + ", rating=" + rating + ", postId=" + postId + ", topicsId=" + topicsId + ", eventId=" + eventId + ", username=" + username + '}';
    }

}
