package com.coderslab.entity;
// Generated Oct 30, 2017 8:02:56 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student",
         catalog = "bes"
)
public class Student implements java.io.Serializable {

    private String username;
    private String fatherName;
    private String motherName;
    private String presentAddress;
    private String permanentAddress;
    private String religion;
    private String nationality;
    private String fatherMobile;
    private String motherMobile;
    private String homeMobile;

    public Student() {
    }

    public Student(String username) {
        this.username = username;
    }

    public Student(String username, String fatherName, String motherName, String presentAddress, String permanentAddress, String religion, String nationality, String fatherMobile, String motherMobile, String homeMobile) {
        this.username = username;
        this.fatherName = fatherName;
        this.motherName = motherName;
        this.presentAddress = presentAddress;
        this.permanentAddress = permanentAddress;
        this.religion = religion;
        this.nationality = nationality;
        this.fatherMobile = fatherMobile;
        this.motherMobile = motherMobile;
        this.homeMobile = homeMobile;
    }

    @Id

    @Column(name = "username", unique = true, nullable = false, length = 60)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "fatherName", length = 60)
    public String getFatherName() {
        return this.fatherName;
    }

    public void setFatherName(String fatherName) {
        this.fatherName = fatherName;
    }

    @Column(name = "motherName", length = 60)
    public String getMotherName() {
        return this.motherName;
    }

    public void setMotherName(String motherName) {
        this.motherName = motherName;
    }

    @Column(name = "presentAddress", length = 65535)
    public String getPresentAddress() {
        return this.presentAddress;
    }

    public void setPresentAddress(String presentAddress) {
        this.presentAddress = presentAddress;
    }

    @Column(name = "permanentAddress", length = 65535)
    public String getPermanentAddress() {
        return this.permanentAddress;
    }

    public void setPermanentAddress(String permanentAddress) {
        this.permanentAddress = permanentAddress;
    }

    @Column(name = "religion", length = 45)
    public String getReligion() {
        return this.religion;
    }

    public void setReligion(String religion) {
        this.religion = religion;
    }

    @Column(name = "nationality", length = 45)
    public String getNationality() {
        return this.nationality;
    }

    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    @Column(name = "fatherMobile", length = 11)
    public String getFatherMobile() {
        return this.fatherMobile;
    }

    public void setFatherMobile(String fatherMobile) {
        this.fatherMobile = fatherMobile;
    }

    @Column(name = "motherMobile", length = 11)
    public String getMotherMobile() {
        return this.motherMobile;
    }

    public void setMotherMobile(String motherMobile) {
        this.motherMobile = motherMobile;
    }

    @Column(name = "homeMobile", length = 11)
    public String getHomeMobile() {
        return this.homeMobile;
    }

    public void setHomeMobile(String homeMobile) {
        this.homeMobile = homeMobile;
    }

    @Override
    public String toString() {
        return "Student{" + "username=" + username + ", fatherName=" + fatherName + ", motherName=" + motherName + ", presentAddress=" + presentAddress + ", permanentAddress=" + permanentAddress + ", religion=" + religion + ", nationality=" + nationality + ", fatherMobile=" + fatherMobile + ", motherMobile=" + motherMobile + ", homeMobile=" + homeMobile + '}';
    }

}
