package com.coderslab.entity;
// Generated Nov 22, 2017 11:40:13 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SubCategory generated by hbm2java
 */
@Entity
@Table(name="sub_category"
    ,catalog="bes"
)
public class SubCategory  implements java.io.Serializable {


     private Integer subCategoryId;
     private String subCategoryName;
     private String description;
     private int categoryId;
     private boolean status;

    public SubCategory() {
    }

	
    public SubCategory(String subCategoryName, int categoryId, boolean status) {
        this.subCategoryName = subCategoryName;
        this.categoryId = categoryId;
        this.status = status;
    }
    public SubCategory(String subCategoryName, String description, int categoryId, boolean status) {
       this.subCategoryName = subCategoryName;
       this.description = description;
       this.categoryId = categoryId;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="subCategoryId", unique=true, nullable=false)
    public Integer getSubCategoryId() {
        return this.subCategoryId;
    }
    
    public void setSubCategoryId(Integer subCategoryId) {
        this.subCategoryId = subCategoryId;
    }

    
    @Column(name="subCategoryName", nullable=false, length=50)
    public String getSubCategoryName() {
        return this.subCategoryName;
    }
    
    public void setSubCategoryName(String subCategoryName) {
        this.subCategoryName = subCategoryName;
    }

    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="categoryId", nullable=false)
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    
    @Column(name="status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


