package com.coderslab.entity;
// Generated Oct 30, 2017 11:39:05 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher",
         catalog = "bes"
)
public class Teacher implements java.io.Serializable {

    private String username;
    private String designation;
    private Date joinDate;
    private String presentAddress;
    private String permanentAddress;
    private String details;

    public Teacher() {
    }

    public Teacher(String username) {
        this.username = username;
    }

    public Teacher(String username, String designation, Date joinDate, String presentAddress, String permanentAddress, String details) {
        this.username = username;
        this.designation = designation;
        this.joinDate = joinDate;
        this.presentAddress = presentAddress;
        this.permanentAddress = permanentAddress;
        this.details = details;
    }

    @Id

    @Column(name = "username", unique = true, nullable = false, length = 60)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "designation", length = 100)
    public String getDesignation() {
        return this.designation;
    }

    public void setDesignation(String designation) {
        this.designation = designation;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "joinDate", length = 10)
    public Date getJoinDate() {
        return this.joinDate;
    }

    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    @Column(name = "presentAddress", length = 65535)
    public String getPresentAddress() {
        return this.presentAddress;
    }

    public void setPresentAddress(String presentAddress) {
        this.presentAddress = presentAddress;
    }

    @Column(name = "permanentAddress", length = 65535)
    public String getPermanentAddress() {
        return this.permanentAddress;
    }

    public void setPermanentAddress(String permanentAddress) {
        this.permanentAddress = permanentAddress;
    }

    @Column(name = "details", length = 65535)
    public String getDetails() {
        return this.details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

    @Override
    public String toString() {
        return "Teacher{" + "username=" + username + ", designation=" + designation + ", joinDate=" + joinDate + ", presentAddress=" + presentAddress + ", permanentAddress=" + permanentAddress + ", details=" + details + '}';
    }

}
