package com.coderslab.entity;
// Generated Oct 28, 2017 6:44:48 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Size;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users",
        catalog = "bes"
)
public class Users implements java.io.Serializable {

    private Integer userId;
    private String authority;
    private Date dob;
    private String email;
    private boolean enabled;
    private String firstName;
    private Boolean gender;
    private String lastName;
    private String mobile;
    private String password;
    private String photo;
    private Date registerDate;
    @Size(min = 1, max = 45, message = "User Name must be between 1 to 45 character")
    private String username;
    private String userType;

    public Users() {
    }

    public Users(String authority, String email, boolean enabled, String password, Date registerDate, String username) {
        this.authority = authority;
        this.email = email;
        this.enabled = enabled;
        this.password = password;
        this.registerDate = registerDate;
        this.username = username;
    }

    public Users(String authority, Date dob, String email, boolean enabled, String firstName, Boolean gender, String lastName, String mobile, String password, String photo, Date registerDate, String username, String userType) {
        this.authority = authority;
        this.dob = dob;
        this.email = email;
        this.enabled = enabled;
        this.firstName = firstName;
        this.gender = gender;
        this.lastName = lastName;
        this.mobile = mobile;
        this.password = password;
        this.photo = photo;
        this.registerDate = registerDate;
        this.username = username;
        this.userType = userType;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "userId", unique = true, nullable = false)
    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Column(name = "authority", nullable = false, length = 40)
    public String getAuthority() {
        return this.authority;
    }

    public void setAuthority(String authority) {
        this.authority = authority;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "dob", length = 10)
    public Date getDob() {
        return this.dob;
    }

    public void setDob(Date dob) {
        this.dob = dob;
    }

    @Column(name = "email", nullable = false, unique = true, length = 100)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "enabled", nullable = false)
    public boolean isEnabled() {
        return this.enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    @Column(name = "firstName", length = 50)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name = "gender")
    public Boolean getGender() {
        return this.gender;
    }

    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    @Column(name = "lastName", length = 50)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Column(name = "mobile", length = 11)
    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Column(name = "password", nullable = false, length = 45)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "photo", length = 225)
    public String getPhoto() {
        return this.photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "registerDate", nullable = false, length = 10)
    public Date getRegisterDate() {
        return this.registerDate;
    }

    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    @Column(name = "username", nullable = false, unique = true, length = 60)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "userType", length = 45)
    public String getUserType() {
        return this.userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    @Override
    public String toString() {
        return "Users{" + "userId=" + userId + ", authority=" + authority + ", dob=" + dob + ", email=" + email + ", enabled=" + enabled + ", firstName=" + firstName + ", gender=" + gender + ", lastName=" + lastName + ", mobile=" + mobile + ", password=" + password + ", photo=" + photo + ", registerDate=" + registerDate + ", username=" + username + ", userType=" + userType + '}';
    }

}
